services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # working_dir: /app
    # depends_on:
    #   - nftDatabase
    # volumes:
    #   - $(pwd)/nftapp.db:.
    environment:
      MY_ENV_VAR_NAME: value321

  # migrations1:
  #   # container_name: service-migrations
  #   # image: service-migrations
  #   build:
  #     context: .
  #     dockerfile: Data/Dockerfile
  #     # target: migrations
  #   depends_on:
  #       - nftDatabase

  # cleanup:
  #   # container_name: service-migrations
  #   # image: service-migrations
  #   build:
  #     context: .
  #     dockerfile: CleanUp/Dockerfile
  #     # target: migrations
  #   depends_on:
  #       - nftDatabase
    
  # nftDatabase:
  #   image: mysql
  #   container_name: mysql
  #   volumes:
  #     - db-volume13:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret123
  #     MYSQL_DATABASE: nftdb
  #   ports:
  #     - 3307:3306

# volumes:
#   db-volume13: